### ISSUE TITLE
FAQ Changes

### ISSUE THREAD

**Issue by capitaladot** [BSData/horus-heresy#1388]
**Lords of War**
 the Rules for taking Lords of War in books such as The Crusade Imperialis Army Lists and Mechanicum Taghmata Army List are overridden by the rules for taking Lords of War in The Horus Heresy: Age of Darkness Rulebook
- [x] Militia, 
- [ ] Solar Aux, 
- [ ] Mechanicum, 
- [ ] 'todes, 
- [ ] Game System
- [ ] Questoris Knights

**Game System**
- [ ] Update Field Artillery Weapons (Page 176) Replace the quad launcher (frag) weapon profile with the following:
- [ ] Update Special Rules (Page 172) Under the heading Sniper
- [ ] Update Special Rules (Page 169) Under the heading Preferred Enemy
- [ ] Update Reserves (Page 147) Under the heading Arriving from Reserve
- [ ] Update Panoply of War (Page 131) Add the following bullet point to the list of available Super-heavy vehicles under the title Panoply of War
- [ ] Update Vehicles and Ordnance Weapons (Page 71) Replace the entire paragraph headed Vehicles and Ordnance Weapons 
- [ ] Update Perils of the Warp (Page 29) Add the following to the end of the first paragraph under the heading Perils of the Warp

**Mechanicum**
- [x] Update Scoria (weapon profiles) #1433
- [x] Update Graviton Weapons (Page 177) Replace the graviton imploder weapon profile #1433
- [x] Update Termite #1433

**Solar Aux**
- [x] Update Lord Marshal Ireton MaSade
- [ ] Update Displacer Matrix (Page 17)
- [ ] Update Termite

**Militia**
- [ ] Update Traitor Only – Cult Horde
- [ ] Update Termite (and Dedicated Transport options)

**Legion**
- [ ] Update Termite
- [x] Update Drop Pod #1435
- [ ] Give Legion Dreadnought access to Legion Drop Pod
- [x] Update Legion Dreadnought Drop Pod  #1435
- [x] Update Deathstorm Drop Pod #1435
- [x] Update Anvillus #1435
- [x] Update Kharybdis #1435 
- [ ] Update Space Wolf Compulsory Troop Restrictions
- [ ] Update Primarch Leman Russ Armour)
- [ ] Allow one HQ per 1000 points for Space Wolves
- [ ] Update Sekhmet
- [ ] Update Osiron (Elites Only)
- [ ] Update Combi Grenade and Volkite
- [ ] Update Legiones Astartes (Raven Guard) to nerf Jump Troops
- [ ] Update Alvarax Maun to keep him from using a Termite
- [ ] Update Vulkan: The Draken Scale
- [ ] Update Legiones Astartes (Salamanders) : Promethean Gift
- [ ] Update Lorgar : Dark Fortune
- [ ] Update World Eaters Legion Specific Units (Page 53) Under the heading Chainaxes, 
- [ ] Update Spearhead-Centurion Castrmen Orth (Page 48)
- [ ] Update Konrad Curze (Page 42) Under the heading Special Rules add the following bullet point: • Hit & Run
- [ ] Update Under the sub-heading The Nightmare Mantle 
- [ ] Update Legiones Astartes (Night Lords) (Page 36) Under the heading A Talent for Murder r
- [ ] Update The Aetos Dios
- [ ] Update The Tormentor
- [ ] Update The Primarch Perturabo (Page 27) Under the sub-heading Relentless Strategist
- [ ] Update Narthecium (Page 132)
- [ ] Update Boarding Shields
- [ ] Update Combat shields confer a 6+ invulnerable save, increased to 5+ in close combat. 
- [ ] Update Augury Scanner (Page 131)
- [ ] Update Rite of War: Sky Hunter Phalanx (Page 102) Under the bullet point Rapid Encirclement
- [x] Update Legion Seeker Squad (Page 48) sergeant combi weapon
- [x] Update Legion Seeker Squad (Page 48) combi weapon cost
- [ ] Update Dreadnought Talon (Page 33)
- [ ] Update Apothecarion Detachment (Page 32)  Unit Composition
- [ ] Update Implacable Advance (Page 30)
- [x] Update Veteran Tactics (Page 28) In the Veteran Tactics box-out, replace the bullet point Marksmen with the following: • Stalkers
- [ ] Update Legion Chaplain Consul (Page 20) Replace the text under the bullet point Wargear
- [x] Update Legion Champion Consul (Page 19) Under the heading Wargear add the following bullet point: • A Legion Champion may take a Paragon blade for +20 points. 
- [ ] Update Legion Master of Signal Consul (Page 19) Under the heading Special Rules, amend the bullet point Bombardment 
- [ ] Update Some of Cassian Dracos Reborn’s Cyberthurgy powers 
- [ ] Update to remove Legion Specific Wargear options from all named characters

**Knights**
- [ ] Update Porphyrion interaction with Questoris Ranks

**'todes**
- [x] Update Legio Custodes Special Rule Preternatural Skill
- [x] Update Legio Custodes Wargear Praesidium Shield
- [x] Update Arae-shrikes (Page 243)
- [x] Update Solerite Power Gauntlets & Power Talons (Page 244)
- [x] Update Adrastus Bolt Caliver (Page 245)
- [x] Update Legio Custodes Shield Captain (Page 252
- [x] Update Constantin Valdor (Page 256)
- [x] Update Legio Custodes Contemptor-Achillus Dreadnought (Page 262
- [x] Update Legio Custodes Agamatus Jetbike Squadron (Page 272
- [x] Update Legio Custodes Telemon Heavy Dreadnought

**Comment by thebiggeordiegeek** [comment]
Hey guys

Just wondering how this is coming along, a few people have been grumbling about it.

I know you guys are all volunteers do not trying to have a go, but the length of time this is taking is causing some aggro for event organisers as we have to double check stuff with BattleScribe at the moment.

**Comment by zopha** [comment]
@thebiggeordiegeek I'm just back after a break so I can't comment on how it's coming along. Do you have a top three from the FAQ that you'll like to see included?

**Comment by capitaladot** [comment]
Which event organizers?

**Comment by thebiggeordiegeek** [comment]
I only know UK events, but Company of Legends, Spartanax 2nd Sedition, Blood and Glory, 30k Frontier, King Fluff, Heresy.Scot and Element Games are asking people to not use BattleScribe at the moment due to the FAQs not being implemented.

I was at an event a few weeks ago and it came up a few times, someone had brought the Tormentor to a 3000 point game, when it’s only allowed in 3001 games now, and cyber-familiars all
over the place for Custodes Shield Captains.

**Comment by Mayegelt** [comment]
Solar Aux
  Update Lord Marshal Ireton MaSade
  Update Displacer Matrix (Page 17)
  Update Termite
Militia
  Update Traitor Only – Cult Horde
  Update Termite (and Dedicated Transport options)

These seem to all be fixed now i think.

**Comment by capitaladot** [comment]
Fixed botched Deathstorm update.

**Comment by MountyChris** [comment]
Legion Heralds also need an update. 
Gained Fearless , Implacable advance and access to Terminator Armour.

**Comment by Mayegelt** [comment]
All of these have been fixed over time.
