### ISSUE TITLE
Horus Heresy 2.0 Tracking

### ISSUE THREAD

**Issue by nstephenh** [BSData/horus-heresy#2070]
We're all excited for 2.0. Let's create a Github issue where people can see the current stage of things and potentially volunteer to add more data. 
If you would like to take a task, please reply to the comment so nobody else will try and do it.

- [x] Finish checklists
### Main Rulebook

- [x] Check special rules for changes from phase 3
- [x] Page numbers for special rules

- [x] Check unit types for changes from phase 3
- [x] Page numbers for unit types and sub-types

### Liber Both (Core space marine rules from both books)
- [x] Ranged Weapon Profiles (& page numbers)
- [x] Melee Weapon Profiles (& page numbers)
- [x] Ranged Weapon Selection Entries
- [x] Melee Weapon Selection Entries
- [x] Check Special Rules + page numbers

Here is a big list. I can check to see what is checked off already later. But we can use it as a main list.

MAIN LEGION BOOKS
- [x] **HQ**
- - [x] Praetor
- - [x] Cata Praetor
- - [x] Tart Praetor
- - [x] Centurion
- - [x] Cata Centurion
- - [x] Tart Centurion
- - [x] Command Squad
- - [x] Cata Command Squad
- - [x] Tart Command Squad
- - [x] Damocles Command Rhino

- [x] **Elties**
- - [x] Veterans
- - [x] Terminator Cata
- - [x] Terminator Tart
- - [x] Destroyer Assault
- - [x] Mortalis Destroyers
- - [x] Apothecary Detachment 
- - [x] Techmarine Detachment 
- - [x] Contemptor Dreadnought
- - [x] Rapier Battery 

- [x] **Troops**
- - [x] Tactical
- - [x] Despoiler
- - [x] Assault
- - [x] Breachers
- - [x] Tactical Support
- - [x] Reconnaissance
- - [x] Scouts

- [x] **Dedicated Transports**
- - [x] Rhino
- - [x] Drop Pod
- - [x] Dreadnought Drop Pod
- - [x] Termite Assault Drill

- [x] **Fast Attack** 
- - [x] Seekers
- - [x] Outriders
- - [x] Sabres
- - [x] Sky-Hunters
- - [x] Javelins
- - [x] Proteus Land Speeders
- - [x] Storm Eagle
- - [x] Xiphon
- - [x] Dreadclaw Drop Pod

- [x] **Heavy Support**
- - [x] Leviathan
- - [x] Deredeo
- - [x] Heavy Support Squad
- - [x] Predator
- - [x] Sicaran
- - [x] Sicaran Arcus 
- - [x] Sicaran Punisher 
- - [x] Sicaran Venator
- - [x] Sicaran Omega
- - [x] Kratos 
- - [x] Land Raider Proteus Carrier
- - [x] Land Raider Proteus Explorator
- - [x] Vindicator
- - [x] Land Raider Spartan
- - [x] Scorpius 
- - [x] Arquitor 
- - [x] Fire Raptor
- - [x] Deathstorm Drop Pod
- - [x] Kharybdis Assault Claw

- [x] **LoW** 
- - [x] Cerberus
- - [x] Typhon
- - [x] Glaive
- - [x] Fellblade
- - [x] Falchion
- - [x] Thunderhawk Gunship
- - [x] Sokar Stormbird
- - [x] Mastodon

- [x] **Fortifications** 
- - [x] Defence Line
- - [x] Fortified Wall
- - [x] Imperial Bunker

- [x] **Legion Consuls** - **Claimed by UrsinePatriarch**
- - [x] Librarian
- - [x] Esoterist
- - [x] Master of Signals (no bike or jetbike)
- - [x] Champion
- - [x] Forgelord 
- - [x] Primus Medicae 
- - [x] Siege Breaker
- - [x] Chaplain
- - [x] Vigilator (no bike or jetbike or jump pack)
- - [x] Pathfinder (no bike or jetbike or jump pack)
- - [x] Moritat (no bike or jetbike)
- - [x] Praevian (no bike or jetbike or jump pack)
- - [x] Delegatus
- - [x] Herald
- - [x] Armistos (no bike or jetbike or jump pack)
- - [x] Mortifactor (no bike or jetbike or jump pack)
- [x] **Cata**
- - [x] Librarian in Cata
- - [x] Esoterist in Cata
- - [x] Champion in Cata
- - [x] Forgelord in Cata
- - [x] Primus Medicae in Cata
- - [x] Siege Breaker in Cata
- - [x] Chaplain in Cata
- - [x] Delegatus in Cata
- - [x] Herald in Cata
- - [x] Mortifactor in Cata
- [x] **Tartaros**
- - [x] Librarian in Tart
- - [x] Esoterist in Tart
- - [x] Champion in Tart
- - [x] Forgelord in Tart
- - [x] Primus Medicae in Tart
- - [x] Siege Breaker in Tart
- - [x] Chaplain in Tart
- - [x] Delegatus on Tart
- - [x] Herald in Tart
- - [x] Mortifactor in Tart

### Liber Astartes
- [x] Dark Angels - **Partially claimed by RevivedTitan**
- - [x] Wargear Profiles
- - [x] Unit Profiles
- - [x] Special Rules
- - [x] Legion-specific weapons added to unaligned units

- [x] White Scars
- - [x] Wargear Profiles
- - [x] Unit Profiles
- - [x] Special Rules
- - [x] Legion-specific weapons added to unaligned units

- [x] Space Wolves
- - [x] Wargear Profiles
- - [x] Unit Profiles
- - [x] Special Rules
- - [x] Legion-specific weapons added to unaligned units

- [x] Imperial Fists - **Claimed by UrsinePatriarch**
- - [x] Wargear Profiles
- - [x] Unit Profiles
- - [x] Special Rules
- - [x] Legion-specific weapons added to unaligned units

- [x] Blood Angels
- - [x] Wargear Profiles
- - [x] Unit Profiles
- - [x] Special Rules
- - [x] Legion-specific weapons added to unaligned units

- [x] Iron Hands
- - [x] Wargear Profiles
- - [x] Unit Profiles
- - [x] Special Rules
- - [x] Legion-specific weapons added to unaligned units

- [x] Ultramarines
- - [x] Wargear Profiles
- - [x] Unit Profiles
- - [x] Special Rules
- - [x] Legion-specific weapons added to unaligned units

- [x] Salamanders - **Claimed by MillionsLikeUs**
- - [x] Wargear Profiles
- - [x] Unit Profiles
- - [x] Special Rules
- - [x] Legion-specific weapons added to unaligned units

- [x] Raven Guard
- - [x] Wargear Profiles
- - [x] Unit Profiles
- - [x] Special Rules
- - [x] Legion-specific weapons added to unaligned units

### Liber Hereticus

- [x] Emperors Children - **Medonoop claimed**
- - [x] Wargear Profiles
- - [x] Unit Profiles
- - [x] Special Rules
- - [x] Legion-specific weapons added to unaligned units

- [x] Iron Warriors - 
- - [x] Wargear Profiles
- - [x] Unit Profiles
- - [x] Special Rules
- - [x] Legion-specific weapons added to unaligned units

- [x] Nightlords - **Claimed by MrDark**
- - [x] Wargear Profiles
- - [x] Unit Profiles
- - [x] Special Rules
- - [x] Legion-specific weapons added to unaligned units

- [x] World Eaters 
- - [x] Wargear Profiles
- - [x] Unit Profiles
- - [x] Special Rules
- - [x] Legion-specific weapons added to unaligned units

- [x] Death Guard - **Claimed by UrsinePatriarch**
- - [x] Wargear Profiles
- - [x] Unit Profiles
- - [x] Special Rules
- - [x] Legion-specific weapons added to unaligned units

- [x] Thousand Sons - **Claimed by Arkangelmark5**
- - [x] Wargear Profiles
- - [x] Unit Profiles
- - [x] Special Rules
- - [x] Legion-specific weapons added to unaligned units

- [x] Sons of Horus
- - [x] Wargear Profiles
- - [x] Unit Profiles
- - [x] Special Rules
- - [x] Legion-specific weapons added to unaligned units

- [x] Word Bearers
- - [x] Wargear Profiles
- - [x] Unit Profiles
- - [x] Special Rules
- - [x] Legion-specific weapons added to unaligned units

- [x] Alpha Legion
- - [x] Wargear Profiles
- - [x] Unit Profiles
- - [x] Special Rules
- - [x] Legion-specific weapons added to unaligned units

- [x] Put it all together

- [x] Universal RoWs
- [x] Legion Specific RoWs

- [x] **Legacies of The Age of Darkness**
- [x] **Expanded Unit Types** ADD TO GST
- - [x] Fortification 
- - [x] Building Sub-type 
- - [x] Emplacement Sub-type 
- - [x] Barricade Sub-type 
- - [x] Massive Sub-type 
- [x] **HQ**
- - [x] Legion Primus Nullificator Consul - **Claimed by UrsinePatriarch**
- - [x] Legion Warmonger Consul - **Claimed by UrsinePatriarch**
- [x] **Elite**
- - [x] Legion Nullificator Squad
- - [x] Legion Castra Ferrum Dreadnought Talon
- [x] **Troops**
- - [x] Legion Terminator Indomitus Squad 
- [x] **Fast Attack**
- - [x] Legion Spatha Attack Bike Squadron 
- - [x] Legion Tarantula Sentry Gun Battery 
- - [x] Legion Avenger Strike Fighter 
- - [x] Legion Thunderbolt Fighter 
- - [x] Legion Primaris-Lightning Strike Fighter 
- [x] **Heavy Support**
- - [x] Legion Land Raider Phobos 
- - [x] Legion Land Raider Achilles 
- - [x] Legion Basilisk Squadron 
- - [x] Legion Medusa Squadron 
- - [x] Legion Whirlwind 
- - [x] Legion Caestus Assault Ram 
- - [x] Legion Malcador Assault Tank Squadron 
- - [x] Legion Minotaur Battery 
- [x] **LoW**
- - [x] Legion Stormblade 
- - [x] Legion Thunderhawk Transporter 
- - [x] Legion Marauder Bomber 
- - [x] Legion Marauder Destroyer 
- - [x] Legion Baneblade 
- - [x] Legion Banehammer 
- - [x] Legion Stormlord 
- - [x] Legion Shadowsword 
- - [x] Legion Stormsword 
- - [x] Legion Macharius Heavy Tank Squadron
- - [x] Legion Macharius Omega Heavy Tank
- - [x] Legion Crassus Armoured Assault Transport
- - [x] Legion Praetor Armoured Assault Launcher
- [x] **Fortificaitions** ADD TO GST
- - [x] Firestorm Redoubt (Legacies of The Age of Darkness)
- - [x] Vengeance Weapon Battery (Legacies of The Age of Darkness)
- - [x] Void Shield Generator (Legacies of The Age of Darkness)
- - [x] Skyshield Landing Pad (Legacies of The Age of Darkness)
- - [x] Fortress of Redemption (Legacies of The Age of Darkness)
- - [x] Aquila Strongpoint (Legacies of The Age of Darkness)
- - [x] Primus Redoubt (Legacies of The Age of Darkness)
- - [x] Hammerfall Bunker (Legacies of The Age of Darkness) 
- [x] **Legion Specific Units**
- - [x] Farith Redloss 
- - [x] Holguin 
- - [x] Deathwing Terminator Cataphractii Companions 
- - [x] Deathwing Terminator Tartaros Companions 
- - [x] Firewing Enigmatus Cabal 
- - [x] Excindio Battle-automata 
- - [x] Falcon’s Claws 
- - [x] Tsolmon Khan 
- - [x] Fenrisian Wolf Pack 
- - [x] Ætos Dios 
- - [x] Iron-Father Autek Mor 
- - [x] Shadrak Meduson 
- - [x] Judiciar Aster Crohne 
- - [x] Honoured Telemechrus 
- - [x] Fulmentarus Terminator Squad 
- - [x] Locutarus Storm Squad 
- - [x] Cassian Dracos Reborn 
- - [x] Lord Chaplain Nomus Rhy’tan 
- - [x] Xiaphas Jurr 
- - [x] Moritat-Prime Kaedes Nex 
- - [x] Strike Captain Alvarex Maun 
- - [x] Rylanor the Unyielding 
- - [x] The Tormentor 
- - [x] Iron Havocs 
- - [x] Erasmus Golg 
- - [x] Nârik Dreygur 
- - [x] Kyr Vhalen 
- - [x] Flaymaster Mawdyrm Llansahai 
- - [x] Kheron Ophion of the Kyroptera 
- - [x] Nakrid Thole 
- - [x] Shabran Darr 
- - [x] Gahlan Surlak 
- - [x] Crysos Mortug 
- - [x] Marshal Durak Rask 
- - [x] Ammitara Occult Intercession Cabal
- - [x] Reaver Aggressor Squad 
- - [x] Tybalt Marr 
- - [x] Autilon Skorr 

- [x] **Exemplary Battles of Age of Darkness & Exemplary Battles - The Scouring of Gildens Star**
- - [x] Imperial Fists Huscarl Squad
- - [x] Night Lords Atramentar Squad
- - [x] Iron Warriors Dominator Cohort 
- - [x] World Eater Red Hand Destroyer Assault Squad
- - [x] Dark Angels Inner Circle Knights Cenobium - Order of the Broken Claws
- - [x] Death Guard Mortus Poisoner Squad
- - [x] Ultramarines Nemesis Destroyer Squad
- - [x] White Scars Dark Sons of Death
- - [x] Emperor’s Children Sun Killer Squad 
- - [x] Raven Guard Deliverers Squad
- - [x] Word Bearers Procurators

### Legion Placeholders (including Legacies and Exemplary Battles)
- - [x] Dark Angels
- - [x] Emperors Children
- - [x] Iron Warriors
- - [x] White Scars
- - [x] Space Wolves
- - [x] Imperial Fists
- - [x] Nightlords
- - [x] Blood Angels
- - [x] Iron Hands
- - [x] World Eaters
- - [x] Ultramarines
- - [x] Death Guard
- - [x] Thousand Sons
- - [x] Sons of Horus
- - [x] Wordbearers
- - [x] Salamanders
- - [x] Ravenguard
- - [x] Alpha Legion

### Legion Hidden Reconfiguration for Alpha Legion
- - [x] Dark Angels
- - [x] Emperor's Children
- - [x] Iron Warriors
- - [x] White Scars
- - [x] Space Wolves
- - [x] Imperial Fists
- - [x] Night Lords
- - [x] Blood Angels
- - [x] Iron Hands
- - [x] World Eaters
- - [x] Ultramarines
- - [x] Death Guard
- - [x] Thousand Sons
- - [x] Sons of Horus
- - [x] Wordbearers
- - [x] Salamanders
- - [x] Raven Guard

**Comment by Mayegelt** [comment]
That was the plan to do one as per the post in discussions linked below.  But if you want to make a list GP for it.

https://github.com/BSData/horus-heresy/discussions/2067

**Comment by nstephenh** [comment]
Ah I missed that. Thank you!

**Comment by nstephenh** [comment]
Removed liber panopticon fan dex. Hopefully can be available in another repo at some point but we have more pressing things to work on.

**Comment by OtterlyOlive** [comment]
I am looking at automated creation of profiles, starting with the Sabre Tanks 😊

**Comment by UrsinePatriarch** [comment]
I'll be doing Fast Attack as you requested, but I'll also be discussing data structure/formatting with Alphalas as he and I have worked together before on other repos and systems.

**Comment by nstephenh** [comment]
@UrsinePatriarch Sounds good. I spoke to him this morning and I understand how he does selection entries now, so I'll be working on creating those lists soon. See: https://github.com/BSData/horus-heresy/issues/2086. I'll likely restore the selection entry groups that existed in 6ecfb5664982be8636df057e1387ededb022c99a if you want to restore them to the cat or need the IDs.

**Comment by Mayegelt** [comment]
Here is a big list. I can check to see what is checked off already later. But we can use it as a main list.

MAIN LEGION BOOKS
- [ ] HQ
- [ ] Praetor
- [ ] Cata Praetor
- [ ] Tart Praetor
- [ ] Centurion
- [ ] Cata Centurion
- [ ] Tart Centurion
- [ ] Command Squad
- [ ] Cata Command Squad
- [ ] Tart Command Squad
- [ ] Damocles Command Rhino

- [ ] Elties
- [ ] Veterans
- [ ] Terminator Cata
- [ ] Terminator Tart
- [ ] Destroyer Assault
- [ ] Mortalis Destroyers
- [ ] Apothecary Detachment
- [ ] Techmarine Detachment
- [ ] Contemptor Dreadnought
- [ ] Rapier Battery

Troops
- [ ] Tactical
- [ ] Despoiler
- [ ] Assault
- [ ] Breachers
- [ ] Tactical Support
- [ ] Reconnaissance
- [ ] Scouts

- [ ] Dedicated Transports
- [ ] Rhino
- [ ] Drop Pod
- [ ] Dreadnought Drop Pod
- [ ] Termite Assault Drill

- [ ] Fast Attack
- [ ] Seekers
- [ ] Outriders
- [ ] Sabres
- [ ] Sky-Hunters
- [ ] Javelins
- [ ] Proteus Land Speeders
- [ ] Storm Eagle
- [ ] Xiphon
- [ ] Dreadclaw Drop Pod

- [ ] Heavy Support
- [ ] Leviathan
- [ ] Deredeo
- [ ] Heavy Support Squad
- [ ] Predator
- [ ] Sicaran
- [ ] Sicaran Arcus
- [ ] Sicaran Punisher
- [ ] Sicaran Venator
- [ ] Sicaran Omega
- [ ] Kratos
- [ ] Land Raider Proteus Carrier
- [ ] Land Raider Proteus Explorator
- [ ] Vindicator
- [ ] Land Raider Spartan
- [ ] Scorpius
- [ ] Arquitor
- [ ] Fire Raptor
- [ ] Deathstorm Drop Pod
- [ ] Kharybdis Assault Claw

- [ ] LoW
- [ ] Cerberus
- [ ] Typhon
- [ ] Glaive
- [ ] Fellblade
- [ ] Falchion
- [ ] Thunderhawk Gunship
- [ ] Sokar Stormbird
- [ ] Mastodon

- [ ] Legion Consuls
- [ ] Librarian
- [ ] Esoterist
- [ ] Master of Signals (no bike or jetbike)
- [ ] Champion
- [ ] Forgelord
- [ ] Primus Medicae
- [ ] Siege Breaker
- [ ] Chaplain
- [ ] Vigilator (no bike or jetbike or jump pack)
- [ ] Pathfinder (no bike or jetbike or jump pack)
- [ ] Moritat (no bike or jetbike)
- [ ] Praevian (no bike or jetbike or jump pack)
- [ ] Delegatus
- [ ] Herald
- [ ] Armistos (no bike or jetbike or jump pack)
- [ ] Mortifactor (no bike or jetbike or jump pack)
- [ ] Librarian in Cata
- [ ] Esoterist in Cata
- [ ] Champion in Cata
- [ ] Forgelord in Cata
- [ ] Primus Medicae in Cata
- [ ] Siege Breaker in Cata
- [ ] Chaplain in Cata
- [ ] Delegatus in Cata
- [ ] Herald in Cata
- [ ] Mortifactor in Cata
- [ ] Librarian in Tart
- [ ] Esoterist in Tart
- [ ] Champion in Tart
- [ ] Forgelord in Tart
- [ ] Primus Medicae in Tart
- [ ] Siege Breaker in Tart
- [ ] Chaplain in Tart
- [ ] Delegatus on Tart
- [ ] Herald in Tart
- [ ] Mortifactor in Tart

- [ ] Next up Legion wargear and units
- [ ] Next up universal RoWs
- [ ] Next up Legion Specific RoWs
- [ ] Next up Legacies of The Age of Darkness
- [ ] Next up Exemplary Battles of Age of Darkness & Exemplary Battles - The Scouring of Gildens Star and any other ones since this post

**Comment by Mayegelt** [comment]
Assault, Despoiler and Destroyer squads added by Toreador13.
Looks good on a glance. Any issues can be checked once we do the once over at the end.

**Comment by Toreador13** [comment]
I will look over it tonight and just see if I can validate it unless someone steps up.

**Comment by Toreador13** [comment]
It does look to be complete. Marking it off the list.

**Comment by Mayegelt** [comment]
Someone reported recon squads don't have their weapon options.

**Comment by Mayegelt** [comment]
Someone else is also reporting similar issues with Breachers not having the volkite swap option.

**Comment by UrsinePatriarch** [comment]
As an official aside to post here, I am working through Fast Attack still but got busy with a friend from out of town. Should have more results this weekend and apologize for the holdup.

**Comment by Toreador13** [comment]
Having issues with my access, so I thought I would update. Have finished Seekers, the Dreadclaw Drop pod and Night Lord Terror squad. Will push when I can figure out what's wrong.

**Comment by UrsinePatriarch** [comment]
For anyone reading this, I am currently finishing LoW and will begin work on the IW-specific units afterwards.

**Comment by Mayegelt** [comment]
> For anyone reading this, I am currently finishing LoW and will begin work on the IW-specific units afterwards.

I've put that you have claimed them.
Did you also want to do the legacies and exemplary IW stuff as well while at it?
Iron Warriors Dominator Cohort
The Tormentor
Iron Havocs
Erasmus Golg
Nârik Dreygur 
Kyr Vhalen

**Comment by UrsinePatriarch** [comment]
Sure, I'm down.

**Comment by revivedtitan** [comment]
Have we decided if we are going to put legion specific profiles and wargear in the Legion Astartes catalog or if each legion will have their own catalog? I see Ursine was given the green light for Iron Warriors and was curious if the other legion could be started as well.

> > For anyone reading this, I am currently finishing LoW and will begin work on the IW-specific units afterwards.
> 
> I've put that you have claimed them. Did you also want to do the legacies and exemplary IW stuff as well while at it? Iron Warriors Dominator Cohort The Tormentor Iron Havocs Erasmus Golg Nârik Dreygur Kyr Vhalen

**Comment by revivedtitan** [comment]
Claiming:
Sicaran Arcus
Sicaran Punisher
Sicaran Venator

Question for Sicaran Omega and Legion Sicaran
They currently have Hexagrammaton Choice. Should that be removed since its specific to 1st Legion Dark Angels and applies to the army as whole?

**Comment by Mayegelt** [comment]
> Have we decided if we are going to put legion specific profiles and wargear in the Legion Astartes catalog or if each legion will have their own catalog? I see Ursine was given the green light for Iron Warriors and was curious if the other legion could be started as well.
> 
> > > For anyone reading this, I am currently finishing LoW and will begin work on the IW-specific units afterwards.
> > 
> > 
> > I've put that you have claimed them. Did you also want to do the legacies and exemplary IW stuff as well while at it? Iron Warriors Dominator Cohort The Tormentor Iron Havocs Erasmus Golg Nârik Dreygur Kyr Vhalen

Initially we are hosting them all together. It may be that we break them up at a later point.

**Comment by Mayegelt** [comment]
> Claiming: Sicaran Arcus Sicaran Punisher Sicaran Venator
> 
> Question for Sicaran Omega and Legion Sicaran They currently have Hexagrammaton Choice. Should that be removed since its specific to 1st Legion Dark Angels and applies to the army as whole?

Add it in. It only shows for DA

**Comment by revivedtitan** [comment]
Is there set verbiage for selection group names?

Example:

Sponson Weapons:
Sponson Mounted Weapons:
Set of Two Sponson Mounted Weapons:

Another example:

May take any of the following:
May Take:
Any Legion Sicaran may take:

Just want to know what the preferred choice is moving forward so my additions can be consistent.

**Comment by nstephenh** [comment]
In general we try and keep close to the verbage in the book but we don't
really have any standards beyond that when we need to make modifications.

**Comment by UrsinePatriarch** [comment]
I've been a bit freeform with my verbage figuring I can go back and fix them if we ever set down standards.
Currently aiming for concise but accurate titles.

**Comment by revivedtitan** [comment]
Claiming: 

Kratos Squadron
Land Raider Proteus Explorator Squadron 
Scorpius Squadron 
Arquitor Squadron 

*This should finish out heavy support

Inner Circle Knights Cenobium
Inner Circle Knights Cenobium - Order of Broken Claws
Dreadwing Interemptor Squad

**Comment by UrsinePatriarch** [comment]
Just saw this, mate; apologies for sniping the Explorator, but it just got merged with all of my other work last night.
Forgot to check all the way down here instead of just looking at the checklist.

**Comment by revivedtitan** [comment]
All good. I can do the three remaining heavies then and the 1st legions units I mentioned

**Comment by Medonoop** [comment]
Claiming:
Emperor's Children:
Wargear Profiles
Unit Profiles
Special Rules
Rylanor the Unyielding
Emperor’s Children Sun Killer Squad

I've been fleshing out all of the Emperor's Children unique units, fixing the missing rules, upgrades etc. Pretty much ready for a PR but I just saw @UrsinePatriarch's PR which includes some WT and EC changes so I'll wait for that to go through and merge it across. Need to wait for consuls so be completed before trying to add the Phoenix Warden properly.

**Comment by UrsinePatriarch** [comment]
Thanks for the consideration, mate; feel free to change up anything I may have gotten wrong or missed. Best of luck ~

**Comment by figjam-bohica** [comment]
Hello, I'm trying to contribute for the first time and I'm confused about the directions in the contributing file on points cost. Specifically `Set the points here for the difference between the first model and second, or sgt model.`

The unit I'm building is the Iron Hands Gorgon Terminator Squad. The unit is 200pts for 5 models and to add an additional model is 35 points. In battlescribe for the cost do I mark that it is 40pts permodel (200/5) or 35? I apologize for the questions but I'm new here and want to update properly.

**Comment by Mayegelt** [comment]
35pts a model. But then put a unit tax in the selection entry of 60pts
(don't add PTS to sergeant)

**Comment by UrsinePatriarch** [comment]
> * I cannot save the Data File. There are a lot of validation errors in the astartes v.20 file preventing me from saving what I've done. Do I need to remediate those or delete the offending entries?
> * How are dedicated Transports added to the unit? Copy/paste and set the unit max as 1? I don't see it as a category, should it be added?

1) Deleting the entries is not suggested; which Shared Selection Entries (SSEs, the base unit entry) are throwing errors and does it say why?
2) DTs are added with a basic Selection Entry Group; consult the other entries like Tac Squads and Veterans to see how those work.

Overall, I really suggest trying to reverse-engineer (figure out what makes them tick and why) existing entries before diving headfirst into your own work; it helps to figure out how formatting works and what tricks you can use to force the system to obey the logic given by the unit.

**Comment by figjam-bohica** [comment]
Thank you for the warm welcome. I'm going to work on the Iron Hands.

**Comment by Arkangelmark5** [comment]
Thousand Sons Legion Units and Wargear

**Comment by mjfreese** [comment]
Predator squadron claimed and completed,
Claiming Salamanders warlord traits,
Claiming Cassian Dracos Reborn, Nomus Rhytan, Xiaphas Jurr

**Comment by IVLegionnaire** [comment]
Just wanted to ask - whats the best way to highlight errors Ive found in the datafiles?

**Comment by revivedtitan** [comment]
> Just wanted to ask - whats the best way to highlight errors Ive found in the datafiles?

First check if the big/issue has already been submitted and if not add it to the list of bugs in the repo

**Comment by Mayegelt** [comment]
Always make sure you update your data files first as well.

**Comment by revivedtitan** [comment]
Taking the six baneblades variant LoWs

**Comment by Cryorm** [comment]
Anyone start working on the USR reference page number to-do for generic space marines yet? If not, I'll go ahead and start trying to work on them if I can figure out how github works

**Comment by reilly-cuauhtemoc-8178** [comment]
Partially claiming Legion-Specific RoWs (Dark Angels RoWs are WIP).

**Comment by Mayegelt** [comment]
A big push happened today. Almost everything is now done.
Just 2 jobs left for Legions I think.
1) Legion Specific RoW
2) Hide all the wargear that AL shouldn't have from universal and legion specific units that aren't directly attached to the units (Aka taking a Raven's Talon on a Tactical Sergeant, but not hiding them for Dark Furies).

**Comment by daimhinmacfinn** [comment]
Is anyone working on a Custodes .cat? I don't want to make one if someone else already has one 90% done!

**Comment by Mayegelt** [comment]
> Is anyone working on a Custodes .cat? I don't want to make one if someone else already has one 90% done!

There is a placeholders one with points in the Master directory. I believe Alphalas is either going to use that or make his own at some point. Just everything has gone a bit slow over the last couple of months. Now sure when the next release will be, but hopefully should have a lot of legion RoW, and will have a fully functional Sisters of Silence and Solar Auxilia as well as Assassin's in it.

**Comment by daimhinmacfinn** [comment]
I might have a look at writing one in the New Year. I've finished the file I've been working on for WFB6e
