### ISSUE TITLE
Shattered Legions checklist / feedback

### ISSUE THREAD

**Issue by Mayegelt** [BSData/horus-heresy#3349]
- [x] Get IC's to have legion specific wargear
- [x] Vets as troops and give them line
- [x] Units with dedicated transports become support units (Breacher, Despoilers & Tactical, Vets only I think as other slots are currently all non compulsory, though may be an issue for Master of Signal who I think can take a Damocles and technically a retinue for a hero such as a pretor might have the same issue)
- [x] Hibou Khan, Shadrak Meduson added to SL (maybe more???
- [x] Navigator/Davinite Lodge Priest do not show as HQ Options
- [x] Thousand Sons HERO Trait: Does not add the Psyker Unit Sub-Type, but does add the Divination Discipline and requisite Psychic Options. (currently a note is added about this I think, but could be worked out)
- [ ] Thousand Sons MAJOR Trait: Perhaps add a Selectable on all models in the Unit for who gets the Prosperine Wrath weapon... Not sure how to implement well ATM... It seems this Major Trait is flexable as it can trade between models as it is applied at the start or a phase. Maybe have a "Psychic**" amendment to the profiles, though this is a lot of work, and people should know their own units...
